// widgets/angular/widgets/button.component.ts
import { Component, Input, Output, EventEmitter, HostBinding } from '@angular/core';
import { SafeStyle } from "@angular/platform-browser";


@Component({
    selector: 'tm-button',
    templateUrl: 'app/widgets/button.component.html',
    styleUrls: ['app/widgets/button.component.css'],
})
export class ButtonComponent {
    private UIButtonContext = UIButtonContext;
    private MarkerType = MarkerType;

    @HostBinding('attr.data-disabled') @Input() disabled?: boolean = false;

    @Input() label: string = ""
    @Input() target?: string | undefined = undefined
    @Input() openinnew: boolean = false
	@Input() icon?: string | undefined = undefined
	@Input() image?: UrlString | undefined = undefined
    @Input() color?: SafeStyle | undefined = undefined
    @Input() markerType?: MarkerType | undefined = MarkerType.Circle
	@Input() loading: boolean = false
    @Input() small: boolean = false
    @Input() leftbound: boolean = false
    @Input() fullwidth: boolean = false
    @Input() active: boolean = false
    @Input() context: UIButtonContext = UIButtonContext.Default
    @Output() click: EventEmitter<MouseEvent> = new EventEmitter<MouseEvent>()

    constructor() { }
}
<a
	is-button
	class="button"
	[attr.disabled]="disabled ? true : null"
	[attr.href]="target ? target : null"
	[attr.target]="openinnew ? '_blank': null"
	[class.is-leftbound]="leftbound"
	[class.is-loading]="loading"
	[class.is-primary]="context === UIButtonContext.Primary"
	[class.is-success]="context === UIButtonContext.Success"
	[class.is-warning]="context === UIButtonContext.Warning"
	[class.is-danger]="context === UIButtonContext.Danger"
	[class.is-link]="context === UIButtonContext.Link"
	[class.is-minimal]="context === UIButtonContext.Minimal"
	[class.is-small]="small"
	[class.is-fullwidth]="fullwidth"
	[class.is-active]="active"
	[class.has-color]="color !== undefined"
	[class.has-label]="label && label.length > 0"
	[class.has-icon]="icon !== undefined"
	[class.icon-only]="icon && (!label || label.length === 0)"
	[class.is-empty]="(!label || label.length === 0) && !icon && !image"
	[class.stupidbigcolorblock]="markerType === MarkerType.StupidBigColorBlock"
>
	<ng-container *ngIf="icon">
		<span class="icon" [tmInlineSVG]="icon"></span>
	</ng-container>
	<span class="image" *ngIf="image">
		<img src="{{ image }}" style="width: 1.25em;">
	</span>
	<span
		*ngIf="color"
		class="state"
		[class.circle]="markerType === MarkerType.Circle"
		[class.square]="markerType === MarkerType.Square"
		[class.sidebar]="markerType === MarkerType.Sidebar"
		[class.bigrectangle]="markerType === MarkerType.BigRectangle"
		[style.background-color]="color"></span>
	<span *ngIf="label && label.length > 0" class="label">{{ label }}</span>
</a>

// widgets/src/Button.svelte
<style>
	.is-loading {

	}

	.is-primary {

	}

	.is-success {

	}

	.is-warning {

	}

	.is-danger {

	}

	.is-link {

	}

	.is-minimal {

	}

	.is-small {

	}

	.is-fullwidth {

	}

	.is-active {

	}

	.has-label {

	}

	.has-icon {

	}

	.has-only-icon {

	}
</style>

<script>
	import Icon from "./Icon.svelte";
	export let icon = null
	export let label = null;
	export let href = null;
	export let isOpenedInNewWindow = false;

	$: hasHref = href && href.length > 0;
	$: hasLabel = label && label.length > 0;
	$: hasIcon = !!icon;
	$: hasOnlyIcon = icon && (label === undefined || label.length === 0);
</script>

<a
	class="button"
	href={href}
	target={isOpenedInNewWindow ? "_target" : null}>

	{#if hasIcon}
		<Icon icon={icon} />
	{/if}
	{#if hasLabel}
		<span class="label">{ label }</span>
	{/if}
</a>
